export const CodeFileTypes = Object.freeze({
  C:           'c',
  CPP:         'cpp',
  CSHARP:      'cs',
  JAVA:        'java',
  PYTHON:      'py',
  RUBY:        'rb',
  GO:          'go',
  R:           'r',
  JAVASCRIPT:  'js',
  TYPESCRIPT:  'ts',
  JSX:         'jsx',
  TSX:         'tsx',
  HTML:        'html',
  CSS:         'css',
  PHP:         'php',
  SWIFT:       'swift',
  KOTLIN:      'kt',
  RUST:        'rs',
  SCALA:       'scala',
  PERL:        'pl',
  HASKELL:     'hs',
  LUA:         'lua',
  SQL:         'sql',
  DART:        'dart',
  SHELL:       'sh',
  POWERSHELL:  'ps1',
  MARKDOWN:    'md',
});

