services:
  api:
    build: ./api
    ports: ["8081:8081"]
    environment:
      - ROOT_DIR=/srv/homenest/data
      - ONLYOFFICE_JWT_SECRET=${ONLYOFFICE_JWT_SECRET}
      - API_PUBLIC_URL=http://api:8081
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - ONLYOFFICE_URL=${ONLYOFFICE_URL}
      - ONLYOFFICE_FETCH_URL=${ONLYOFFICE_FETCH_URL}
    volumes:
      - ${HOST_DATA_DIR:-${HOME}/HomeNest/data}:/srv/homenest/data

  documentserver:
    image: onlyoffice/documentserver:latest
    ports: ["8080:80"]
    environment:
      - JWT_ENABLED=true
      - JWT_SECRET=${ONLYOFFICE_JWT_SECRET}
    depends_on: [api]
